### ISSUE TITLE
default value for within variable is not working

### ISSUE THREAD

**Issue by McPringle** [lukecarr/nightly-check#11]
I tried to use your action but it is not working as intended. This is the relevant part of my own action:

```yaml
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.nightly-check.outputs.changes }}
    steps:
      - id: nightly-check
        name: Check for changes since last nightly
        uses: lukecarr/nightly-check@v0.3.1
```

As you can see, I don't have `within` specified, so it should use your default value. But the variable is empty as you can see in the output of your action (see empty `after` value):

```
test -z $(git rev-list --after="" abd68737727b4f5624c055f5c47be1206e89dc99) && echo "changes=true" >> $GITHUB_OUTPUT
```

Then I tried to specify the `within` value in my action. Same problem, the variable is still empty.
